### ISSUE TITLE
Special graph constructors ignore implicit typemax

### ISSUE THREAD

**Issue by mcognetta** [JuliaGraphs/SpecialGraphs.jl#8]
The graphs implemented here subtype `AbstractGraph{T}`, but the number of nodes is generally stored as an `Int`. This allows things like `PathGraph{Int8}(10000)` to work, which could cause errors downstream.

**Comment by matbesancon** [comment]
Indeed, I wanted to parametrize things a tad more. PR welcome otherwise

**Comment by mcognetta** [comment]
Closed via #9.
